project_id = "tbmvoekntmaxxvfouxuy"

[functions.list-admin-users]
verify_jwt = false

[functions.toggle-admin-status]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false
